# Generated by Django 3.1 on 2020-08-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_workshopregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='governorate',
            field=models.CharField(choices=[('AHMADI', 'Ahmadi'), ('AL_ASIMAH', 'Al-Asimah'), ('FARWANIYA', 'Farwaniya'), ('HAWALLI', 'Hawalli'), ('JAHRA', 'Jahra'), ('MUBARAK_AL_KABEER', 'Mubarak Al-Kabeer')], default='AHMADI', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
