# Generated by Django 3.1 on 2020-08-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200819_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reference_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
