# Generated by Django 3.1 on 2020-08-21 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200820_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_id_number',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
    ]
